name: Build Windows EXE with PyInstaller
on: [workflow_dispatch]  # Runs on every push (customize as needed)

jobs:
  build:
    runs-on: windows-latest  # Windows runner
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install run dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install build dependencies 
        run: |
          pip install pyinstaller

      # 4. Run PyInstaller
      - name: Build tl_worker EXE
        run: |
          python -m PyInstaller --collect-all selenium_stealth --onefile tl_worker.py
      #- name: Build ke_server EXE
      #  run: |
      #    python -m PyInstaller --collect-all selenium_stealth --onefile ke_server.py

      # 5. Upload the EXE as an artifacts (for download)
      - name: Upload tl_worker
        uses: actions/upload-artifact@v4
        with:
          name: autotb_exe
          path: dist/tl_worker.exe  # Path to the generated EXE
      
      #- name: Upload ke_server
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: ke_server_exe
      #    path: dist/ke_server.exe
